#!/bin/bash
#
# This file was automatically generated by s2e-env at {{ creation_time }}
#
# This script is used to run the S2E analysis. Additional QEMU command line
# arguments can be passed to this script at run time.
#

FIRMWARE="{{ firmware }}"
FIRMWARE_LABEL="{{ firmware_label }}"
FUZZ_IN="AFL/${FIRMWARE_LABEL}_fuzz_in"
FUZZ_OUT="AFL/${FIRMWARE_LABEL}_fuzz_out"
SEED_FILE="{{ seed }}"
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

cd "$SCRIPT_DIR"
mkdir -p "$FUZZ_IN"
if [ ! -f "$FUZZ_IN/$(basename -- "$SEED_FILE")" ]; then
	cp -f "$SEED_FILE" "$FUZZ_IN/"
fi

if [ ! -d "$FUZZ_OUT" ]; then
	mkdir -p "$FUZZ_OUT"
else
	echo "Reusing existing AFL output directory $FUZZ_OUT"
fi

exec afl-fuzz -i "$FUZZ_IN" -o "$FUZZ_OUT" -t 100000 uEmu
